### ISSUE TITLE
NOT FOUND Errors from solve.py

### ISSUE THREAD

**Issue by jh888** [relet/wordbase-solver#1]
I have a couple of games I've tried to use solve.py on that have a number of already played words.  I'm getting a not found error on a couple of the words, which I think mean that they're not in the dictionary.  I've tried adding them using addword.py and then even removing the .idx file, but the error message persists.

For example:

./solve.py game1 OILER BALERS RECURES SEER CRAPE ESTER UTES SISTER
Word list restored from dump. yay.
NOT FOUND: 'RECURES'

./solve.py game2 STROMA ESCAPERS#0 AIRLINE PERSALT MANILA#0 CNIDARIANS MAIRS#1 ALIENATOR MAINER LARIAT MISREAD SCALERS MAIR ENAMORED COLTAN NARIAL CHINAS INHALE SCALER INLACES CHILES CLINTONIA HIRES CLICHES CHILE CLACHS COMICAL CLAIMS CHIRAL CLACH CHAL CLICHE CHALS CLERICAL HAILER CELIACS HALE CERTAIN HALES CLERICALS HALER ASCERTAINS HARES CELIAC CHISEL CLERIC HILAR EARACHES
Generating word index and attack vectors.
NOT FOUND: 'MAINER'

Is there a way to verify if the word made it into the dictionary file, or is the error caused by something else?  Thanks!

**Comment by relet** [comment]
It's true, the message is a bit unspecific. You get it either when the word is not in the dictionary, or if it cannot be built on the board. 

The most common causes for the error are
- You forgot a move, and the script is trying to build a word on the wrong side of the table.
- You chose the wrong move from a choice (e.g. ESCAPERS#0 instead of ESCAPERS#1) and the moves would not be possible with the other option.
- The word is not the dictionary (RECURES isn't), but you should have resolved that with addword.py

When you used ./addword.py, you can be pretty sure the word is in the dictionary. But if you want to check yourself, the dictionaries are just sqlite databases. So if you open them with a sqlite client (or send the query from a python script), you can check with 

```
$ sqlite3 dict/twl.sqlite
sqlite> .headers on
sqlite> select * from words where word=='WORD';
id|word
176847|WORD
```

You will not get an answer for words that do not exist.

```
sqlite> select * from words where word=='NONEXIST';
sqlite>
```

If you upload the game file somewhere, I can help you check what went wrong.

**Comment by relet** [comment]
I added some friendlier error messages, as in

```
# ./solve.py example1 hello
Cannot play 'HELLO' at this stage of the game.

# ./solve.py example1 - sponsal
Cannot play 'SPONSAL' at this stage of the game.
Hint: The word is playable for the other player. Maybe you skipped a move.

# ./solve.py example1 nonexist
'NONEXIST' is not in my dictionary, use addword.py to remedy this.
```

If you do a git pull on the repository, you should get either of these.

**Comment by jh888** [comment]
Thanks so much relet.  I got the new solve.py and before adding the words to the new dictionary it gave the not in dictionary error, as expected.  After adding the words to the dictionary it comes back with the cannot play at this stage of the game error, but I believe it to be in error for both games.  Below is the game file for the simpler of the two cases.  RECURES is the second word played by orange and starts on 4,5 and ends on 6,1.  The command I used that failed was: ./solve.py game1 OILER BALERS RECURES SEER CRAPE ESTER UTES SISTER   

http://pastebin.ca/2961817

**Comment by relet** [comment]
I take it everything works correctly now? 
At least it does when I try your example (Next suggestion is CREPIEST).

**Comment by jh888** [comment]
It wasn't, but I just tried removing the .idx file since updating the dictionary and it worked.  Not sure what was wrong before.  Thanks.

**Comment by jh888** [comment]
Sorry to bother again, but I can't figure out what's wrong with this other game.  The same starting letter M is used three times in a row, but for the third word it says the word can't be played.  The M is at 4,5.  The game file looks correct, and I've deleted the index file and get the same error each time.  Thanks again.

http://pastebin.ca/2962298

./solve.py game2 STROMA ESCAPERS#0 AIRLINE PERSALT MANILA#0 CNIDARIANS MAIRS#1 ALIENATOR MAINER
Word list restored from dump. yay.
Cannot play 'MAINER' at this stage of the game.

**Comment by relet** [comment]
Regarding the index file: It stores all possible moves from any position of the game. Of course, if the dictionary changes, or the game board changes, this has to be deleted. 

Currently, the game is smart enough to detect that the game board has changed and ignores the old index file. It's not too difficult to detect that the dictionary has changed, but that doesn't get detected so far. 

In your second example, the script is correct. ALIENATOR cuts off the letter M that has been used before to create the M words. 

I noticed that your game board does not contain any bombs. Since that is quite unusual, maybe you just forgot to mark them on the game board - in that case the boards the game displays can be different from the ones you are actually playing on.

**Comment by relet** [comment]
I'll close the issue then. Feel free to keep commenting.

**Comment by jh888** [comment]
The bomb thing makes good sense, I should have thought of that.  Thanks relet.

**Comment by relet** [comment]
You're totally welcome. Since I wrote the script first and foremost to prove some theories I had about the game, I'm really happy to get some feedback from other players and know their experiences.
